-- Generated from KOReader frontend/dispatcher.lua, the category="none"
-- entries whose event takes no argument. Regenerate with
-- scripts/gen_koreader_actions.py when KOReader gains actions.
return {
    { section = "General", actions = {
        { event = "ShowBookMetadataArchive", title = "Book metadata archive" },
        { event = "ShowBookmarkBrowser", title = "Bookmark browser" },
        { event = "ShowCollList", title = "Collections" },
        { event = "ShowCollectionsSearchDialog", title = "Collections search" },
        { event = "CycleDictionaryPresets", title = "Cycle through dictionary presets" },
        { event = "ShowDictionaryLookup", title = "Dictionary lookup" },
        { event = "ShowColl", title = "Favorites" },
        { event = "Home", title = "File browser" },
        { event = "ShowGestureOverview", title = "Gesture overview" },
        { event = "ShowHist", title = "History" },
        { event = "SearchHistory", title = "History search" },
        { event = "MenuSearch", title = "Menu search" },
        { event = "ShowNotebookFile", title = "Notebook file" },
        { event = "OpenNextOrPreviousFileInFolder", title = "Open next file in last book folder" },
        { event = "OpenLastDoc", title = "Open previous document" },
        { event = "Screenshot", title = "Screenshot" },
        { event = "ShowMenu", title = "Show menu" },
        { event = "ShowWikipediaLookup", title = "Wikipedia lookup" },
    } },
    { section = "Reader", actions = {
                { event = "AddCurrentLocationToStack", title = "Add current location to history" },
        { event = "Back", title = "Back" },
        { event = "GoBackLink", title = "Back to previous location" },
        { event = "ShowBookCover", title = "Book cover" },
        { event = "ShowBookDescription", title = "Book description" },
        { event = "ShowBookInfo", title = "Book information" },
        { event = "ShowBookMap", title = "Book map" },
        { event = "ShowBookStatus", title = "Book status" },
        { event = "SearchBookmark", title = "Bookmark search" },
        { event = "ShowBookmark", title = "Bookmarks" },
        { event = "ZoomFactorChange", title = "Change zoom factor" },
        { event = "ClearLocationStack", title = "Clear location history" },
        { event = "CycleHighlightAction", title = "Cycle highlight action" },
        { event = "CycleHighlightStyle", title = "Cycle highlight style" },
        { event = "CycleOverlapStyle", title = "Cycle page overlap style" },
        { event = "EditBookTweak", title = "Edit book-specific style tweak" },
        { event = "ExportAnnotations", title = "Export annotations" },
        { event = "GotoFirstBookmark", title = "First bookmark" },
        { event = "GoToBeginning", title = "First page" },
        { event = "GoForwardLink", title = "Forward to next location" },
        { event = "ShowFulltextSearchInput", title = "Fulltext search" },
        { event = "GoToStartPage", title = "Fulltext search: go back to original page" },
        { event = "ShowGotoDialog", title = "Go to page" },
        { event = "GoToPinnedPage", title = "Go to pinned page" },
        { event = "GotoLastBookmark", title = "Last bookmark" },
        { event = "ShowFindAllResults", title = "Last fulltext search results" },
        { event = "GoToEnd", title = "Last page" },
        { event = "GoToLatestBookmark", title = "Latest bookmark" },
        { event = "GotoNextBookmarkFromPage", title = "Next bookmark" },
        { event = "GotoNextChapter", title = "Next chapter" },
        { event = "ShowPageBrowser", title = "Page browser" },
        { event = "PinPage", title = "Pin current page" },
        { event = "GotoPreviousBookmarkFromPage", title = "Previous bookmark" },
        { event = "GotoPrevChapter", title = "Previous chapter" },
        { event = "GoToRandomPage", title = "Random page" },
        { event = "FlushSettings", title = "Save book metadata" },
        { event = "SelectNextPageLink", title = "Select next link in current page" },
        { event = "SelectPrevPageLink", title = "Select previous link in current page" },
        { event = "ShowConfigMenu", title = "Show bottom menu" },
        { event = "ShowSkimtoDialog", title = "Skim document" },
        { event = "ShowToc", title = "Table of contents" },
        { event = "ToggleBookTweak", title = "Toggle book-specific style tweak" },
        { event = "ToggleBookmark", title = "Toggle bookmark" },
        { event = "ToggleBookmarkFlipping", title = "Toggle bookmark flipping" },
        { event = "ToggleChapterProgressBar", title = "Toggle chapter progress bar" },
        { event = "ToggleHandmadeFlows", title = "Toggle custom hidden flows" },
        { event = "ToggleHandmadeToc", title = "Toggle custom TOC" },
        { event = "ToggleFloatingPunctuation", title = "Toggle hanging punctuation" },
        { event = "TogglePageFlipping", title = "Toggle page flipping" },
        { event = "TogglePageChangeAnimation", title = "Toggle page turn animations" },
        { event = "ToggleReadingOrder", title = "Toggle page turn direction" },
        { event = "TogglePanelZoomSetting", title = "Toggle panel zoom" },
        { event = "ToggleReflow", title = "Toggle reflow" },
        { event = "ToggleFooterMode", title = "Toggle status bar" },
        { event = "ToggleStyleTweaks", title = "Toggle style tweaks" },
        { event = "ToggleTapLinks", title = "Toggle tap-to-follow links" },
        { event = "StartHighlightIndicator", title = "Toggle text selection mode" },
        { event = "TranslateCurrentPage", title = "Translate current page" },
    } },
    { section = "File browser", actions = {
        { event = "Back", title = "Back" },
        { event = "ShowCloudStorage", title = "Cloud storage" },
        { event = "ShowFileSearch", title = "File search" },
        { event = "ShowFolderShortcutsDialog", title = "Folder shortcuts" },
        { event = "FolderUp", title = "Folder up" },
        { event = "ShowGotoDialog", title = "Go to page" },
        { event = "ShowSearchResults", title = "Last file search results" },
        { event = "RefreshContent", title = "Refresh content" },
        { event = "ShowPlusMenu", title = "Show plus menu" },
        { event = "ToggleSelectMode", title = "Toggle select mode" },
    } },
    { section = "Screen", actions = {
        { event = "FullRefresh", title = "Full screen refresh" },
        { event = "ShowFlDialog", title = "Show frontlight dialog" },
        { event = "ToggleFlashOnChapterBoundaries", title = "Toggle flashing on chapter boundaries" },
        { event = "ToggleNoFlashOnSecondChapterPage", title = "Toggle flashing on chapter's 2nd page" },
        { event = "ToggleFlashOnPagesWithImages", title = "Toggle flashing on pages with images" },
        { event = "ToggleFrontlight", title = "Toggle frontlight" },
        { event = "ToggleNightMode", title = "Toggle night mode" },
    } },
    { section = "Device", actions = {
        { event = "IgnoreTouchInput", title = "Disable touch input" },
        { event = "TempGSensorOn", title = "Enable accelerometer for 5 seconds" },
        { event = "Exit", title = "Exit KOReader" },
        { event = "ExitScreensaver", title = "Exit sleep screen" },
        { event = "SwapPageTurnButtons", title = "Invert left-side page-turn buttons" },
        { event = "InvertRotation", title = "Invert rotation" },
        { event = "RequestPowerOff", title = "Power off" },
        { event = "RequestReboot", title = "Reboot the device" },
        { event = "Restart", title = "Restart KOReader" },
        { event = "IterateRotation", title = "Rotate by 90° CCW" },
        { event = "ShowNetworkInfo", title = "Show network info" },
        { event = "RequestSuspend", title = "Sleep" },
        { event = "RequestUSBMS", title = "Start USB storage" },
        { event = "ToggleGSensor", title = "Toggle accelerometer" },
        { event = "ToggleFullscreen", title = "Toggle Fullscreen" },
        { event = "ToggleKeyRepeat", title = "Toggle key repeat" },
        { event = "LockGSensor", title = "Toggle lock auto rotation to current orientation" },
        { event = "IgnoreHoldCorners", title = "Toggle long-press on corners" },
        { event = "SwapRotation", title = "Toggle orientation" },
        { event = "ToggleWifi", title = "Toggle Wi-Fi" },
        { event = "InfoWifiOff", title = "Turn off Wi-Fi" },
        { event = "InfoWifiOn", title = "Turn on Wi-Fi" },
    } },
}
